Link binaries statically
When this plugin is used in a container which does not have `glibc` (or
an equivalent library) installed, it will exit with the following error:
    > Error: fork/exec […]: no such file or directory

When the binary is statically linked this error will not occur.

Fixes #26